targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.model.dart
      json_serializable:
        generate_for:
          include:
            - lib/**.model.dart
