// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAa02Sqk-KKfGcjmjTaP9cCfh6Euzb8J4',
    appId: '1:1076464861257:web:7c05ea41dfda7c0d0fbf98',
    messagingSenderId: '1076464861257',
    projectId: 'flutter-appventor',
    authDomain: 'flutter-appventor.firebaseapp.com',
    storageBucket: 'flutter-appventor.appspot.com',
    measurementId: 'G-8V0E8EY95L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlFQ2C-5F7MmciIhpysDwvTE1FhY_oLP8',
    appId: '1:1076464861257:android:111d65d0378354180fbf98',
    messagingSenderId: '1076464861257',
    projectId: 'flutter-appventor',
    storageBucket: 'flutter-appventor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC52k0QTKFX-nqZp65V2VnYRAQbbtWPAhU',
    appId: '1:1076464861257:ios:2496d4a1191498230fbf98',
    messagingSenderId: '1076464861257',
    projectId: 'flutter-appventor',
    storageBucket: 'flutter-appventor.appspot.com',
    iosClientId: '1076464861257-62akt26miipf1qlj6gvnknsuluprjo3t.apps.googleusercontent.com',
    iosBundleId: 'com.appventor.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC52k0QTKFX-nqZp65V2VnYRAQbbtWPAhU',
    appId: '1:1076464861257:ios:2496d4a1191498230fbf98',
    messagingSenderId: '1076464861257',
    projectId: 'flutter-appventor',
    storageBucket: 'flutter-appventor.appspot.com',
    iosClientId: '1076464861257-62akt26miipf1qlj6gvnknsuluprjo3t.apps.googleusercontent.com',
    iosBundleId: 'com.appventor.app',
  );
}
