// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTXGZ6iy4d8UeMv3-0-y2hZZInT9KL8c',
    appId: '1:167570291473:web:ae819cb55dd49d01682ab0',
    messagingSenderId: '167570291473',
    projectId: 'flutter-appventor-dev',
    authDomain: 'flutter-appventor-dev.firebaseapp.com',
    storageBucket: 'flutter-appventor-dev.appspot.com',
    measurementId: 'G-Z0C7VJEPXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewdBGqoTbNaeHvxieF20eoXzMHc6pkq8',
    appId: '1:167570291473:android:45e71ca320eac11f682ab0',
    messagingSenderId: '167570291473',
    projectId: 'flutter-appventor-dev',
    storageBucket: 'flutter-appventor-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGEa_x3sKXD-wN_RMxu66ZFZv-TOeFpE',
    appId: '1:167570291473:ios:936347512fc9b61b682ab0',
    messagingSenderId: '167570291473',
    projectId: 'flutter-appventor-dev',
    storageBucket: 'flutter-appventor-dev.appspot.com',
    iosClientId: '167570291473-his363km9evc8vm8of6c2qgmvkjsj48h.apps.googleusercontent.com',
    iosBundleId: 'com.appventor.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGEa_x3sKXD-wN_RMxu66ZFZv-TOeFpE',
    appId: '1:167570291473:ios:936347512fc9b61b682ab0',
    messagingSenderId: '167570291473',
    projectId: 'flutter-appventor-dev',
    storageBucket: 'flutter-appventor-dev.appspot.com',
    iosClientId: '167570291473-his363km9evc8vm8of6c2qgmvkjsj48h.apps.googleusercontent.com',
    iosBundleId: 'com.appventor.dev',
  );
}
