// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_beta.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ03odYDa12vKLapvVcLDpktvEhovxLaE',
    appId: '1:1015971606161:web:9bb2d93fde393c5f4b9930',
    messagingSenderId: '1015971606161',
    projectId: 'flutter-appventor-beta',
    authDomain: 'flutter-appventor-beta.firebaseapp.com',
    storageBucket: 'flutter-appventor-beta.appspot.com',
    measurementId: 'G-558CL1VH76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3H6yvgn2uzUU4n_nDnJUctOmnDgkZNJs',
    appId: '1:1015971606161:android:2603b0a9cc4a22944b9930',
    messagingSenderId: '1015971606161',
    projectId: 'flutter-appventor-beta',
    storageBucket: 'flutter-appventor-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwUHw9tYVduJD73jh8d_IrvKNTNbMNFKc',
    appId: '1:1015971606161:ios:a747b1da4ed4fe354b9930',
    messagingSenderId: '1015971606161',
    projectId: 'flutter-appventor-beta',
    storageBucket: 'flutter-appventor-beta.appspot.com',
    iosClientId: '1015971606161-ua5ki9ichnh4lomivsb5g0sj3kvbp053.apps.googleusercontent.com',
    iosBundleId: 'com.appventor.beta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwUHw9tYVduJD73jh8d_IrvKNTNbMNFKc',
    appId: '1:1015971606161:ios:a747b1da4ed4fe354b9930',
    messagingSenderId: '1015971606161',
    projectId: 'flutter-appventor-beta',
    storageBucket: 'flutter-appventor-beta.appspot.com',
    iosClientId: '1015971606161-ua5ki9ichnh4lomivsb5g0sj3kvbp053.apps.googleusercontent.com',
    iosBundleId: 'com.appventor.beta',
  );
}
